
platform :ios, '5.0'

# Recommended to keep GPUImage up-to-date
pod 'GPUImage', :head

# For regular projects
#pod 'NBUImagePicker'

# Optional for dynamic logging
pod 'NBULog'

# Optional for on-device log console
pod 'LumberjackConsole'

# For development
#pod 'NBUKit', :head
#pod 'NBUKit', :path => '../../NBUKit'
pod 'NBUImagePicker', :path => '../'

