
platform :ios, '8.0'
use_frameworks!

target 'PickerDemo' do
    
# Recommended to keep GPUImage up-to-date
pod 'GPUImage', :git => 'https://github.com/BradLarson/GPUImage.git'

# For regular projects
#pod 'NBUImagePicker'

# Optional for dynamic logging
pod 'NBULog'

# Optional for on-device log console
pod 'LumberjackConsole'

# For development
pod 'NBUImagePicker', :path => '../'

end
